services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,${ROOT_DOMAIN}
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000,${APP_DOMAIN}
      - DATABASE_URL=${DB_URL}
      - REDIS_URL=redis://:horilla_pass@redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  migrate:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DB_URL}
    depends_on:
      - redis
    restart: "no"

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass horilla_pass
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  staticfiles:
  media:
  postgres_data:
  redis_data:
