services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DB_URL}
    command: sh ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
      - ./media:/app/media
